pipeline {
    agent any

    parameters {
        booleanParam(name: 'destroy', defaultValue: false, description: 'Destroy infrastructure')
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/M-Hazan/DevOps-Projects.git'
            }
        }

        stage('Terraform') {
            steps {
                withCredentials([
                    string(credentialsId: 'aws-access-key', variable: 'AWS_ACCESS_KEY_ID'),
                    string(credentialsId: 'aws-secret-key', variable: 'AWS_SECRET_ACCESS_KEY')
                ]) {
                    dir('first-jenkins-pipeline') {
                        echo 'Now in first-jenkins-pipeline directory'
                        sh 'terraform init'
                        if (params.destroy == true) {
                            sh 'terraform destroy -auto-approve'
                        } else {
                            sh 'terraform apply -auto-approve'
                        }
                    }
                }
            }
        }

        stage('Ansible') {
            steps {
                dir('first-jenkins-pipeline') {
                    sh 'ansible-playbook -i inventory.ini website.yml'
                }
            }
        }
    }
}

